import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import FooterSection from "./components/footer/footer-section";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['900', '800', '700', '600', '500', '400', '300', '200', '100']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
